config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :users
  resources :giftcards

end

app/models/giftcard.rb
class Giftcard < ActiveRecord::Base
    belongs_to :user
    validates :user_id, presence: true
    validates :title, presence: true
    validates :message, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :giftcards
    validates :name, presence: true, uniqueness: true
    validates :email, presence: true
    validates :gender, presence: true
    
    validates_inclusion_of :gender, :in => %w(Male Female)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/giftcards_controller.rb
class GiftcardsController < ApplicationController
  def index
    # This method is a stub. You should replace everything in here with your own implementation
    #@giftcards = []
    @giftcards = Giftcard.all
  end

  def show
    # This method is a stub. You should replace everything in here with your own implementation
    #@giftcard = Object.new
    @giftcard = Giftcard.find(params[:id])
  end

  def new
    # This method is a stub. You should replace everything in here with your own implementation
    #@giftcard = Object.new
    #@users = []
    @giftcard = Giftcard.new
    @users = User.all
  end

  def create
    # This method is a stub. You should replace everything in here with your own implementation
    # You may need to use strong parameters to create a User, please read:
    # http://edgeguides.rubyonrails.org/action_controller_overview.html#strong-parameters
    #flash[:notice] = 'Gift Card successfully created!'
    #redirect_to action: :index
    @giftcard = Giftcard.new(giftcard_params)
    
    if @giftcard.save
      redirect_to @giftcard
    else
      @users = User.all
      render 'new'
    end
  end

  private

  def giftcard_params
    # This method is a stub. Used for strong params. Complete your implementation below
    params.require(:giftcard).permit(:title, :message, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    # This method is a stub. You should replace everything in here with your own implementation
    #@users = [create_fake_user]
    @users = User.all
  end

  def show
    # This method is a stub. You should replace everything in here with your own implementation
    #@user = create_fake_user
    @user = User.find(params[:id])
  end

  def new
    # This method is a stub. You should replace everything in here with your own implementation
    #@user = create_fake_user
    @user = User.new
  end

  def create
    # This method is a stub. You should replace everything in here with your own implementation
    # You may need to use strong parameters to create a User, please read:
    # http://edgeguides.rubyonrails.org/action_controller_overview.html#strong-parameters
    #flash[:notice] = 'User successfully created!'
    #redirect_to action: :index
    @user = User.new(user_params)
    
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
    # This method is a stub. Used for strong params. Complete your implementation below
    params.require(:user).permit(:name, :email, :gender)
  end

  def create_fake_user
    user = Object.new
    def user.id() 1 end
    def user.name() 'Fake name' end
    def user.email() 'fake@email.com' end
    def user.gender() 'Some Invalid Gender' end
    user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_class_for(flash_type)
    {
      success:'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/views/giftcards/index.html.slim
.row
  .col-md-12
    h1 Gift Cards

    table.table.table-hover
      thead
        tr
          th Title
          th Message
          th Owner

      tbody
        - @giftcards.each do |giftcard|
          tr.clickable onclick = "window.location = '#{giftcard_path(giftcard)}';"
            td= giftcard.title
            td= giftcard.message
            td= giftcard.user.email

    = link_to 'New Gift Card', new_giftcard_path, class: 'btn btn-warning'

app/views/giftcards/new.html.slim
.row
  .col-md-12
    h1 New Gift Card
    p Please fill in the fields below

= simple_form_for(@giftcard, class: 'form-horizontal') do |f|
  == render 'shared/errors', object: f.object
  = f.input :title, label: 'Title', wrapper_html: {class: 'col-sm-10'}
  = f.input :message, label: 'Message', wrapper_html: {class: 'col-sm-10'}
  = f.input :user_id, collection: @users, label: 'Owner', label_method: proc {|u| u.name}, value_method: proc {|u| u.id}, wrapper_html: {class: 'col-sm-4'}

  .clear_float
  div class='col-sm-2'
    = f.submit 'Create Gift Card', class: 'btn btn-success'

app/views/giftcards/show.html.slim
.row
  .col-md-12
    h1 Gift Card Details

    .bold Title
    = @giftcard.title

    .bold Message
    = @giftcard.message

    .bold User Name
    = @giftcard.user.name

    .bold User Email
    = @giftcard.user.email

    .clear_float
    br
    = link_to 'Back', giftcards_path, class: 'btn btn-default'

app/views/home/index.html.slim
h1 Welcome!

h4 Select an item from the side menu to begin.

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Gift Card
    = stylesheet_link_tag '//fonts.googleapis.com/css?family=Roboto:400,300'
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    - flash.each do |type, message|
      div class="alert #{alert_class_for(type)} alert-dismissible fade in"
        button type="button" class="close" data-dismiss="alert" ×
        = message
    == render 'shared/menu'
    #page
      = yield

app/views/shared/_errors.html.slim
- if object.errors.any?
  #error_explanation
    .alert.alert-error
      | The form contains #{pluralize(object.errors.count, 'errors')}.
    ul
      - object.errors.full_messages.each do |msg|
        li = msg

app/views/shared/_menu.html.slim
#menu-wrapper
  ul.sidebar-nav
    li.sidebar-brand
     = link_to root_path do
      .well
        span Gift Cards Application
    li
      = link_to 'Users', users_path
    li
      = link_to 'Gift Cards', giftcards_path

app/views/users/index.html.slim
.row
  .col-md-12
    h1 Users

    table.table.table-hover
      thead
        tr
          th Name
          th Email
          th Gender

      tbody
        - @users.each do |user|
          tr.clickable onclick = "window.location = '#{user_path(user)}';"
            td= user.name
            td= user.email
            td= user.gender

    = link_to 'New User', new_user_path, class: 'btn btn-warning'

app/views/users/new.html.slim
.row
  .col-md-12
    h1 New User
    p Please fill in the fields below

= simple_form_for(@user, class: 'form-horizontal') do |f|
  == render 'shared/errors', object: f.object
  = f.input :name, label: 'Name', wrapper_html: {class: 'col-sm-10'}
  = f.input :email, label: 'Email', wrapper_html: {class: 'col-sm-10'}
  = f.input :gender, collection: %w(Female Male), label: 'Gender', wrapper_html: {class: 'col-sm-4'}

  .clear_float
  div class='col-sm-2'
    = f.submit 'Create User', class: 'btn btn-success'

app/views/users/show.html.slim
.row
  .col-md-12
    h1 User Details

    .bold Name
    = @user.name

    .bold Email
    = @user.email

    .bold Gender
    = @user.gender

    .clear_float
    br
    = link_to 'Back', users_path, class: 'btn btn-default'